import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function GlobalNav() {
  return (
    <nav className="w-full bg-black/75 border-b border-white/10 px-8 py-4 flex items-center gap-8 font-semibold text-zinc-200 z-50">
      <Link href="/" className="text-lg font-black tracking-tight text-amber-400 hover:text-amber-300 transition">
        NodeWatch
      </Link>
      <div className="flex gap-6 ml-6 text-sm">
        <Link href="/mvp" className="hover:text-white transition">
          Electric MVP
        </Link>
        <Link href="/leaderboard" className="hover:text-white transition">
          Game Vault
        </Link>
        <Link href="/team" className="hover:text-white transition">
          NBA Teams
        </Link>
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#0a0a0a]">
        <GlobalNav />
        <div className="flex-1 flex flex-col">{children}</div>
      </body>
    </html>
  );
}
